// <auto-generated />
using System;
using Library.DataAccess.DataBase.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Library.DataAccess.Migrations
{
    [DbContext(typeof(LibraryDBContext))]
    [Migration("20240917102825_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.AccessGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.AccessGroupPermission", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("GroupId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("AccessGroupPermission");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            PermissionId = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 1,
                            PermissionId = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 1,
                            PermissionId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 1,
                            PermissionId = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 2,
                            PermissionId = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.AuthorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a250f8f0-05de-408c-8115-4bf4cb315afd"),
                            Birthday = new DateTime(1943, 9, 17, 10, 28, 25, 210, DateTimeKind.Utc).AddTicks(1112),
                            Country = "Belarus",
                            FirstName = "name0",
                            LastName = "LastName0"
                        },
                        new
                        {
                            Id = new Guid("cf9b7ddb-935d-4306-9917-e05945fcf7dc"),
                            Birthday = new DateTime(2002, 9, 17, 10, 28, 25, 210, DateTimeKind.Utc).AddTicks(1150),
                            Country = "Belarus",
                            FirstName = "name1",
                            LastName = "LastName1"
                        },
                        new
                        {
                            Id = new Guid("b8e0f869-377a-45e9-b9d1-d84c97e0a2d8"),
                            Birthday = new DateTime(1934, 9, 17, 10, 28, 25, 210, DateTimeKind.Utc).AddTicks(1154),
                            Country = "Belarus",
                            FirstName = "name2",
                            LastName = "LastName2"
                        },
                        new
                        {
                            Id = new Guid("f41faa71-95d2-484c-b800-c27e2ac73648"),
                            Birthday = new DateTime(1959, 9, 17, 10, 28, 25, 210, DateTimeKind.Utc).AddTicks(1158),
                            Country = "Belarus",
                            FirstName = "name3",
                            LastName = "LastName3"
                        },
                        new
                        {
                            Id = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            Birthday = new DateTime(2005, 9, 17, 10, 28, 25, 210, DateTimeKind.Utc).AddTicks(1186),
                            Country = "Belarus",
                            FirstName = "name4",
                            LastName = "LastName4"
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<int>("BookType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReturnTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ClientId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3cba0e69-adf1-4c87-b95f-c192db04d323"),
                            AuthorId = new Guid("f41faa71-95d2-484c-b800-c27e2ac73648"),
                            BookType = 0,
                            Description = "3cba0e69-adf1-4c87-b95f-c192db04d323",
                            Genre = "0",
                            ISBN = "9789740640578",
                            Title = "3cba0e69-adf1-4c87-b95f-c192db04d323"
                        },
                        new
                        {
                            Id = new Guid("6efa8a67-bce1-4379-a4ea-e3e68c6b1372"),
                            AuthorId = new Guid("cf9b7ddb-935d-4306-9917-e05945fcf7dc"),
                            BookType = 0,
                            Description = "6efa8a67-bce1-4379-a4ea-e3e68c6b1372",
                            Genre = "1",
                            ISBN = "9793678148501",
                            Title = "6efa8a67-bce1-4379-a4ea-e3e68c6b1372"
                        },
                        new
                        {
                            Id = new Guid("8a703c97-b7c8-4ecc-ac88-ccd02bd008e4"),
                            AuthorId = new Guid("f41faa71-95d2-484c-b800-c27e2ac73648"),
                            BookType = 0,
                            Description = "8a703c97-b7c8-4ecc-ac88-ccd02bd008e4",
                            Genre = "2",
                            ISBN = "9796706749176",
                            Title = "8a703c97-b7c8-4ecc-ac88-ccd02bd008e4"
                        },
                        new
                        {
                            Id = new Guid("aa0ea0e0-e0f3-41fc-b41f-c7b979b02626"),
                            AuthorId = new Guid("a250f8f0-05de-408c-8115-4bf4cb315afd"),
                            BookType = 0,
                            Description = "aa0ea0e0-e0f3-41fc-b41f-c7b979b02626",
                            Genre = "3",
                            ISBN = "9782986826911",
                            Title = "aa0ea0e0-e0f3-41fc-b41f-c7b979b02626"
                        },
                        new
                        {
                            Id = new Guid("7fa24084-f4c6-43d2-8534-632c6e689b8d"),
                            AuthorId = new Guid("cf9b7ddb-935d-4306-9917-e05945fcf7dc"),
                            BookType = 0,
                            Description = "7fa24084-f4c6-43d2-8534-632c6e689b8d",
                            Genre = "4",
                            ISBN = "9782380043785",
                            Title = "7fa24084-f4c6-43d2-8534-632c6e689b8d"
                        },
                        new
                        {
                            Id = new Guid("2411f385-19df-4cef-9118-70ca66e9045b"),
                            AuthorId = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            BookType = 0,
                            Description = "2411f385-19df-4cef-9118-70ca66e9045b",
                            Genre = "5",
                            ISBN = "9791973880447",
                            Title = "2411f385-19df-4cef-9118-70ca66e9045b"
                        },
                        new
                        {
                            Id = new Guid("9dc5f4a8-0c60-48ea-b5e0-947b2504fb45"),
                            AuthorId = new Guid("b8e0f869-377a-45e9-b9d1-d84c97e0a2d8"),
                            BookType = 0,
                            Description = "9dc5f4a8-0c60-48ea-b5e0-947b2504fb45",
                            Genre = "6",
                            ISBN = "9799938600710",
                            Title = "9dc5f4a8-0c60-48ea-b5e0-947b2504fb45"
                        },
                        new
                        {
                            Id = new Guid("0f873442-c170-4928-8811-fd62c3569e11"),
                            AuthorId = new Guid("f41faa71-95d2-484c-b800-c27e2ac73648"),
                            BookType = 0,
                            Description = "0f873442-c170-4928-8811-fd62c3569e11",
                            Genre = "7",
                            ISBN = "9790212317904",
                            Title = "0f873442-c170-4928-8811-fd62c3569e11"
                        },
                        new
                        {
                            Id = new Guid("6f3ddc7c-1030-4648-89a6-802e6fb29b16"),
                            AuthorId = new Guid("b8e0f869-377a-45e9-b9d1-d84c97e0a2d8"),
                            BookType = 0,
                            Description = "6f3ddc7c-1030-4648-89a6-802e6fb29b16",
                            Genre = "8",
                            ISBN = "9790948992123",
                            Title = "6f3ddc7c-1030-4648-89a6-802e6fb29b16"
                        },
                        new
                        {
                            Id = new Guid("6402877c-4c6e-4c79-825a-d43ac60a6b14"),
                            AuthorId = new Guid("a250f8f0-05de-408c-8115-4bf4cb315afd"),
                            BookType = 0,
                            Description = "6402877c-4c6e-4c79-825a-d43ac60a6b14",
                            Genre = "9",
                            ISBN = "9784565740892",
                            Title = "6402877c-4c6e-4c79-825a-d43ac60a6b14"
                        },
                        new
                        {
                            Id = new Guid("12844e36-97f0-40b3-9b5c-426597b22b12"),
                            AuthorId = new Guid("b8e0f869-377a-45e9-b9d1-d84c97e0a2d8"),
                            BookType = 0,
                            Description = "12844e36-97f0-40b3-9b5c-426597b22b12",
                            Genre = "0",
                            ISBN = "9796097252453",
                            Title = "12844e36-97f0-40b3-9b5c-426597b22b12"
                        },
                        new
                        {
                            Id = new Guid("769ecdc9-dd7d-453b-b472-19a47d5631e1"),
                            AuthorId = new Guid("b8e0f869-377a-45e9-b9d1-d84c97e0a2d8"),
                            BookType = 0,
                            Description = "769ecdc9-dd7d-453b-b472-19a47d5631e1",
                            Genre = "1",
                            ISBN = "9782668394653",
                            Title = "769ecdc9-dd7d-453b-b472-19a47d5631e1"
                        },
                        new
                        {
                            Id = new Guid("89a6258c-7c1b-48d4-8144-41b834a9ab8f"),
                            AuthorId = new Guid("a250f8f0-05de-408c-8115-4bf4cb315afd"),
                            BookType = 0,
                            Description = "89a6258c-7c1b-48d4-8144-41b834a9ab8f",
                            Genre = "2",
                            ISBN = "9794578146000",
                            Title = "89a6258c-7c1b-48d4-8144-41b834a9ab8f"
                        },
                        new
                        {
                            Id = new Guid("70acad60-1a5a-4c31-bf39-e64f42aa44ef"),
                            AuthorId = new Guid("cf9b7ddb-935d-4306-9917-e05945fcf7dc"),
                            BookType = 0,
                            Description = "70acad60-1a5a-4c31-bf39-e64f42aa44ef",
                            Genre = "3",
                            ISBN = "9796560349871",
                            Title = "70acad60-1a5a-4c31-bf39-e64f42aa44ef"
                        },
                        new
                        {
                            Id = new Guid("ddd1c2fe-bd83-4f10-b1f4-5e0ecf544ab0"),
                            AuthorId = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            BookType = 0,
                            Description = "ddd1c2fe-bd83-4f10-b1f4-5e0ecf544ab0",
                            Genre = "4",
                            ISBN = "9793050300749",
                            Title = "ddd1c2fe-bd83-4f10-b1f4-5e0ecf544ab0"
                        },
                        new
                        {
                            Id = new Guid("6bebcea5-dd7c-4025-95cc-27d6d14980fd"),
                            AuthorId = new Guid("b8e0f869-377a-45e9-b9d1-d84c97e0a2d8"),
                            BookType = 0,
                            Description = "6bebcea5-dd7c-4025-95cc-27d6d14980fd",
                            Genre = "5",
                            ISBN = "9785700247689",
                            Title = "6bebcea5-dd7c-4025-95cc-27d6d14980fd"
                        },
                        new
                        {
                            Id = new Guid("34b4aeef-1857-4d0b-b464-7107a0d7bda9"),
                            AuthorId = new Guid("f41faa71-95d2-484c-b800-c27e2ac73648"),
                            BookType = 0,
                            Description = "34b4aeef-1857-4d0b-b464-7107a0d7bda9",
                            Genre = "6",
                            ISBN = "9791298987395",
                            Title = "34b4aeef-1857-4d0b-b464-7107a0d7bda9"
                        },
                        new
                        {
                            Id = new Guid("66f8d39a-2ea5-4b70-94f6-60c9e3223291"),
                            AuthorId = new Guid("cf9b7ddb-935d-4306-9917-e05945fcf7dc"),
                            BookType = 0,
                            Description = "66f8d39a-2ea5-4b70-94f6-60c9e3223291",
                            Genre = "7",
                            ISBN = "9781846239557",
                            Title = "66f8d39a-2ea5-4b70-94f6-60c9e3223291"
                        },
                        new
                        {
                            Id = new Guid("050dee5d-eac6-4116-8e6e-c8366f406475"),
                            AuthorId = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            BookType = 0,
                            Description = "050dee5d-eac6-4116-8e6e-c8366f406475",
                            Genre = "8",
                            ISBN = "9790103737118",
                            Title = "050dee5d-eac6-4116-8e6e-c8366f406475"
                        },
                        new
                        {
                            Id = new Guid("59df2174-4eeb-4a91-976b-dcc0ba6bf638"),
                            AuthorId = new Guid("f41faa71-95d2-484c-b800-c27e2ac73648"),
                            BookType = 0,
                            Description = "59df2174-4eeb-4a91-976b-dcc0ba6bf638",
                            Genre = "9",
                            ISBN = "9788096939404",
                            Title = "59df2174-4eeb-4a91-976b-dcc0ba6bf638"
                        },
                        new
                        {
                            Id = new Guid("5b2b2451-f39f-4d8e-9829-5e30b2958bb7"),
                            AuthorId = new Guid("cf9b7ddb-935d-4306-9917-e05945fcf7dc"),
                            BookType = 0,
                            Description = "5b2b2451-f39f-4d8e-9829-5e30b2958bb7",
                            Genre = "0",
                            ISBN = "9799137879115",
                            Title = "5b2b2451-f39f-4d8e-9829-5e30b2958bb7"
                        },
                        new
                        {
                            Id = new Guid("0fe2a2e7-3a04-464d-a433-fb478a95fdab"),
                            AuthorId = new Guid("a250f8f0-05de-408c-8115-4bf4cb315afd"),
                            BookType = 0,
                            Description = "0fe2a2e7-3a04-464d-a433-fb478a95fdab",
                            Genre = "1",
                            ISBN = "9795252752005",
                            Title = "0fe2a2e7-3a04-464d-a433-fb478a95fdab"
                        },
                        new
                        {
                            Id = new Guid("2e5efc69-de19-4b37-ae8e-e9d72bd92998"),
                            AuthorId = new Guid("a250f8f0-05de-408c-8115-4bf4cb315afd"),
                            BookType = 0,
                            Description = "2e5efc69-de19-4b37-ae8e-e9d72bd92998",
                            Genre = "2",
                            ISBN = "9787167032549",
                            Title = "2e5efc69-de19-4b37-ae8e-e9d72bd92998"
                        },
                        new
                        {
                            Id = new Guid("73750d59-9374-4f05-8697-fe842fc693f8"),
                            AuthorId = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            BookType = 0,
                            Description = "73750d59-9374-4f05-8697-fe842fc693f8",
                            Genre = "3",
                            ISBN = "9794084632066",
                            Title = "73750d59-9374-4f05-8697-fe842fc693f8"
                        },
                        new
                        {
                            Id = new Guid("97c57e94-fa53-41fc-a99c-d503cba5105e"),
                            AuthorId = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            BookType = 0,
                            Description = "97c57e94-fa53-41fc-a99c-d503cba5105e",
                            Genre = "4",
                            ISBN = "9784197839780",
                            Title = "97c57e94-fa53-41fc-a99c-d503cba5105e"
                        },
                        new
                        {
                            Id = new Guid("b75499cf-fd94-49d4-a3ab-16991931e2e4"),
                            AuthorId = new Guid("f41faa71-95d2-484c-b800-c27e2ac73648"),
                            BookType = 0,
                            Description = "b75499cf-fd94-49d4-a3ab-16991931e2e4",
                            Genre = "5",
                            ISBN = "9789676908520",
                            Title = "b75499cf-fd94-49d4-a3ab-16991931e2e4"
                        },
                        new
                        {
                            Id = new Guid("5954a06e-b5ff-41e0-9822-7a69ed8f63ad"),
                            AuthorId = new Guid("b8e0f869-377a-45e9-b9d1-d84c97e0a2d8"),
                            BookType = 0,
                            Description = "5954a06e-b5ff-41e0-9822-7a69ed8f63ad",
                            Genre = "6",
                            ISBN = "9784013048495",
                            Title = "5954a06e-b5ff-41e0-9822-7a69ed8f63ad"
                        },
                        new
                        {
                            Id = new Guid("92d6fb6e-f09a-46e9-95af-db8353d0a3f1"),
                            AuthorId = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            BookType = 0,
                            Description = "92d6fb6e-f09a-46e9-95af-db8353d0a3f1",
                            Genre = "7",
                            ISBN = "9782350639673",
                            Title = "92d6fb6e-f09a-46e9-95af-db8353d0a3f1"
                        },
                        new
                        {
                            Id = new Guid("f0c30ca7-366b-4b2a-8ff8-31336f205477"),
                            AuthorId = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            BookType = 0,
                            Description = "f0c30ca7-366b-4b2a-8ff8-31336f205477",
                            Genre = "8",
                            ISBN = "9798305684995",
                            Title = "f0c30ca7-366b-4b2a-8ff8-31336f205477"
                        },
                        new
                        {
                            Id = new Guid("55fc435b-0ff4-42a0-8f2c-669c34ec3119"),
                            AuthorId = new Guid("b8e0f869-377a-45e9-b9d1-d84c97e0a2d8"),
                            BookType = 0,
                            Description = "55fc435b-0ff4-42a0-8f2c-669c34ec3119",
                            Genre = "9",
                            ISBN = "9790875063354",
                            Title = "55fc435b-0ff4-42a0-8f2c-669c34ec3119"
                        },
                        new
                        {
                            Id = new Guid("78ba5769-9d1c-49a1-b30a-bbffe0e44017"),
                            AuthorId = new Guid("f41faa71-95d2-484c-b800-c27e2ac73648"),
                            BookType = 0,
                            Description = "78ba5769-9d1c-49a1-b30a-bbffe0e44017",
                            Genre = "0",
                            ISBN = "9792421708733",
                            Title = "78ba5769-9d1c-49a1-b30a-bbffe0e44017"
                        },
                        new
                        {
                            Id = new Guid("e07f5133-ac56-44e6-b2ab-2464058fc796"),
                            AuthorId = new Guid("cf9b7ddb-935d-4306-9917-e05945fcf7dc"),
                            BookType = 0,
                            Description = "e07f5133-ac56-44e6-b2ab-2464058fc796",
                            Genre = "1",
                            ISBN = "9785171857769",
                            Title = "e07f5133-ac56-44e6-b2ab-2464058fc796"
                        },
                        new
                        {
                            Id = new Guid("8ace0c57-ca5c-47b3-a82b-6e6a48ec0978"),
                            AuthorId = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            BookType = 0,
                            Description = "8ace0c57-ca5c-47b3-a82b-6e6a48ec0978",
                            Genre = "2",
                            ISBN = "9785442092301",
                            Title = "8ace0c57-ca5c-47b3-a82b-6e6a48ec0978"
                        },
                        new
                        {
                            Id = new Guid("457b5b8c-82e7-4aef-9652-a26b475a46bf"),
                            AuthorId = new Guid("cf9b7ddb-935d-4306-9917-e05945fcf7dc"),
                            BookType = 0,
                            Description = "457b5b8c-82e7-4aef-9652-a26b475a46bf",
                            Genre = "3",
                            ISBN = "9798081367662",
                            Title = "457b5b8c-82e7-4aef-9652-a26b475a46bf"
                        },
                        new
                        {
                            Id = new Guid("6ff9edb7-6cc6-4112-a1f7-4b96f363432e"),
                            AuthorId = new Guid("cf9b7ddb-935d-4306-9917-e05945fcf7dc"),
                            BookType = 0,
                            Description = "6ff9edb7-6cc6-4112-a1f7-4b96f363432e",
                            Genre = "4",
                            ISBN = "9788665140712",
                            Title = "6ff9edb7-6cc6-4112-a1f7-4b96f363432e"
                        },
                        new
                        {
                            Id = new Guid("ca66d934-9647-4c2e-a387-563a974bd96b"),
                            AuthorId = new Guid("a250f8f0-05de-408c-8115-4bf4cb315afd"),
                            BookType = 0,
                            Description = "ca66d934-9647-4c2e-a387-563a974bd96b",
                            Genre = "5",
                            ISBN = "9784658539426",
                            Title = "ca66d934-9647-4c2e-a387-563a974bd96b"
                        },
                        new
                        {
                            Id = new Guid("71cdf849-4417-423d-af40-cc851e1b090c"),
                            AuthorId = new Guid("b8e0f869-377a-45e9-b9d1-d84c97e0a2d8"),
                            BookType = 0,
                            Description = "71cdf849-4417-423d-af40-cc851e1b090c",
                            Genre = "6",
                            ISBN = "9783083550198",
                            Title = "71cdf849-4417-423d-af40-cc851e1b090c"
                        },
                        new
                        {
                            Id = new Guid("a045d54e-b9c4-45f1-858e-641d13378b1a"),
                            AuthorId = new Guid("f41faa71-95d2-484c-b800-c27e2ac73648"),
                            BookType = 0,
                            Description = "a045d54e-b9c4-45f1-858e-641d13378b1a",
                            Genre = "7",
                            ISBN = "9784666913485",
                            Title = "a045d54e-b9c4-45f1-858e-641d13378b1a"
                        },
                        new
                        {
                            Id = new Guid("f57b959c-266c-443e-9999-29b5157651f2"),
                            AuthorId = new Guid("f41faa71-95d2-484c-b800-c27e2ac73648"),
                            BookType = 0,
                            Description = "f57b959c-266c-443e-9999-29b5157651f2",
                            Genre = "8",
                            ISBN = "9784716783495",
                            Title = "f57b959c-266c-443e-9999-29b5157651f2"
                        },
                        new
                        {
                            Id = new Guid("48ce5717-9e30-4577-99b5-8318b25bf51a"),
                            AuthorId = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            BookType = 0,
                            Description = "48ce5717-9e30-4577-99b5-8318b25bf51a",
                            Genre = "9",
                            ISBN = "9796714051643",
                            Title = "48ce5717-9e30-4577-99b5-8318b25bf51a"
                        },
                        new
                        {
                            Id = new Guid("75a0d61f-7b67-43e8-9e88-043ba7c74170"),
                            AuthorId = new Guid("f41faa71-95d2-484c-b800-c27e2ac73648"),
                            BookType = 0,
                            Description = "75a0d61f-7b67-43e8-9e88-043ba7c74170",
                            Genre = "0",
                            ISBN = "9783541696659",
                            Title = "75a0d61f-7b67-43e8-9e88-043ba7c74170"
                        },
                        new
                        {
                            Id = new Guid("a765856f-3c1e-47c1-a50d-a2898e78686a"),
                            AuthorId = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            BookType = 0,
                            Description = "a765856f-3c1e-47c1-a50d-a2898e78686a",
                            Genre = "1",
                            ISBN = "9796617275856",
                            Title = "a765856f-3c1e-47c1-a50d-a2898e78686a"
                        },
                        new
                        {
                            Id = new Guid("ac41fd90-82f8-4a67-a1db-d550d80944b2"),
                            AuthorId = new Guid("b8e0f869-377a-45e9-b9d1-d84c97e0a2d8"),
                            BookType = 0,
                            Description = "ac41fd90-82f8-4a67-a1db-d550d80944b2",
                            Genre = "2",
                            ISBN = "9799748061299",
                            Title = "ac41fd90-82f8-4a67-a1db-d550d80944b2"
                        },
                        new
                        {
                            Id = new Guid("3023fcf2-e2b6-4d33-b391-1c5f35d2b06d"),
                            AuthorId = new Guid("b8e0f869-377a-45e9-b9d1-d84c97e0a2d8"),
                            BookType = 0,
                            Description = "3023fcf2-e2b6-4d33-b391-1c5f35d2b06d",
                            Genre = "3",
                            ISBN = "9785870447322",
                            Title = "3023fcf2-e2b6-4d33-b391-1c5f35d2b06d"
                        },
                        new
                        {
                            Id = new Guid("cc481dff-1c15-4fef-8d54-629c64b261d7"),
                            AuthorId = new Guid("a250f8f0-05de-408c-8115-4bf4cb315afd"),
                            BookType = 0,
                            Description = "cc481dff-1c15-4fef-8d54-629c64b261d7",
                            Genre = "4",
                            ISBN = "9788471754585",
                            Title = "cc481dff-1c15-4fef-8d54-629c64b261d7"
                        },
                        new
                        {
                            Id = new Guid("b9c3ad0f-3ef5-4215-89f6-7304b37f83b9"),
                            AuthorId = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            BookType = 0,
                            Description = "b9c3ad0f-3ef5-4215-89f6-7304b37f83b9",
                            Genre = "5",
                            ISBN = "9786983195421",
                            Title = "b9c3ad0f-3ef5-4215-89f6-7304b37f83b9"
                        },
                        new
                        {
                            Id = new Guid("218a3563-60dd-4b02-93da-d5c560a82587"),
                            AuthorId = new Guid("b8e0f869-377a-45e9-b9d1-d84c97e0a2d8"),
                            BookType = 0,
                            Description = "218a3563-60dd-4b02-93da-d5c560a82587",
                            Genre = "6",
                            ISBN = "9787142714392",
                            Title = "218a3563-60dd-4b02-93da-d5c560a82587"
                        },
                        new
                        {
                            Id = new Guid("fe5a50da-60ea-4305-87d4-a5cbee048026"),
                            AuthorId = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            BookType = 0,
                            Description = "fe5a50da-60ea-4305-87d4-a5cbee048026",
                            Genre = "7",
                            ISBN = "9783661472010",
                            Title = "fe5a50da-60ea-4305-87d4-a5cbee048026"
                        },
                        new
                        {
                            Id = new Guid("bbf5215e-9c3d-46f6-8ad6-f965d0840faf"),
                            AuthorId = new Guid("197f8fe8-abf4-42ec-a337-87898dd79d5b"),
                            BookType = 0,
                            Description = "bbf5215e-9c3d-46f6-8ad6-f965d0840faf",
                            Genre = "8",
                            ISBN = "9792050613286",
                            Title = "bbf5215e-9c3d-46f6-8ad6-f965d0840faf"
                        },
                        new
                        {
                            Id = new Guid("933399df-720e-4fe3-9583-a4be57d00ed9"),
                            AuthorId = new Guid("cf9b7ddb-935d-4306-9917-e05945fcf7dc"),
                            BookType = 0,
                            Description = "933399df-720e-4fe3-9583-a4be57d00ed9",
                            Genre = "9",
                            ISBN = "9792258296625",
                            Title = "933399df-720e-4fe3-9583-a4be57d00ed9"
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.PermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Create"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Update"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Delete"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Read"
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.UserAccessGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAccessGroup");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            UserId = new Guid("13587099-6e91-4925-aa81-0b51b703cb08"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = new Guid("13587099-6e91-4925-aa81-0b51b703cb08"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9300db8a-fe2f-4044-b10e-51d4c4a592c3"),
                            Email = "9300db8a-fe2f-4044-b10e-51d4c4a592c3@test.test",
                            PasswordHash = "AQAAAAIAAYagAAAAEHoxV1Hw/BC/5MA+cshPJ6Uocl0zqgLDzdp3S2PjJQBJaWOmuHvXuL1LFua5wAcp3Q==",
                            UserName = "user0"
                        },
                        new
                        {
                            Id = new Guid("28e19f4d-ac58-43c7-90df-9c20d904609b"),
                            Email = "28e19f4d-ac58-43c7-90df-9c20d904609b@test.test",
                            PasswordHash = "AQAAAAIAAYagAAAAEGmaVji0RmIDBHYmBycanpgVi0bD+hDqO/7kViSPOkHXxF0IQZRd4990lHBEBgIOvw==",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("05b64e93-2e93-4b35-bd7d-b7dddf3c786d"),
                            Email = "05b64e93-2e93-4b35-bd7d-b7dddf3c786d@test.test",
                            PasswordHash = "AQAAAAIAAYagAAAAEFBrdPd/+2tsUMsEFKeM0p4EaPMeeoyQi7tuxBGadvvkWBdGdgvPoP0knGU82qc3HQ==",
                            UserName = "user2"
                        },
                        new
                        {
                            Id = new Guid("1b622585-cf17-423a-bb0d-d21ba892c730"),
                            Email = "1b622585-cf17-423a-bb0d-d21ba892c730@test.test",
                            PasswordHash = "AQAAAAIAAYagAAAAEJYXai2Mre/W46KoOuupWtdPQYsiO4DKK6yU8IMP2WNpIWEUES+MC0dLZhjYLvo/TQ==",
                            UserName = "user3"
                        },
                        new
                        {
                            Id = new Guid("659ad5a4-943e-48d6-bf02-e09a3ab2c53e"),
                            Email = "659ad5a4-943e-48d6-bf02-e09a3ab2c53e@test.test",
                            PasswordHash = "AQAAAAIAAYagAAAAEOqnvccYT3taSPVKPHd41rzPytn28VvZcvLHvxU27wcASAt2dpksbWBArIDNug8fwA==",
                            UserName = "user4"
                        },
                        new
                        {
                            Id = new Guid("13587099-6e91-4925-aa81-0b51b703cb08"),
                            Email = "admin@admin.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEHKvhHQrDZqG+NJNLCoaKbOEKw0C7/s7b1C1weSU5ySJKgiBFjNrwizZeP9aCJYKHQ==",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.AccessGroupPermission", b =>
                {
                    b.HasOne("Library.DataAccess.DataBase.Entities.AccessGroupEntity", "Group")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.DataAccess.DataBase.Entities.PermissionEntity", "Permission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.BookEntity", b =>
                {
                    b.HasOne("Library.DataAccess.DataBase.Entities.AuthorEntity", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Library.DataAccess.DataBase.Entities.UserEntity", "User")
                        .WithMany("Books")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.UserAccessGroup", b =>
                {
                    b.HasOne("Library.DataAccess.DataBase.Entities.AccessGroupEntity", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.DataAccess.DataBase.Entities.UserEntity", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.AccessGroupEntity", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.AuthorEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.PermissionEntity", b =>
                {
                    b.Navigation("GroupPermissions");
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.UserEntity", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
