// <auto-generated />
using System;
using Library.DataAccess.DataBase.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Library.DataAccess.Migrations
{
    [DbContext(typeof(LibraryDBContext))]
    [Migration("20240921175831_fix-faker")]
    partial class fixfaker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.AccessGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.AccessGroupPermission", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("GroupId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("AccessGroupPermission");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            PermissionId = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 1,
                            PermissionId = 3,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 1,
                            PermissionId = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 1,
                            PermissionId = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 2,
                            PermissionId = 4,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.AuthorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0a3724e-c4fe-4f99-95cf-48f359541fb0"),
                            Birthday = new DateTime(1935, 9, 21, 17, 58, 30, 510, DateTimeKind.Utc).AddTicks(8659),
                            Country = "Jersey",
                            FirstName = "Norman",
                            LastName = "Bashirian"
                        },
                        new
                        {
                            Id = new Guid("ff826d19-91e0-46c3-89a0-80f1c93cef28"),
                            Birthday = new DateTime(2004, 9, 21, 17, 58, 30, 512, DateTimeKind.Utc).AddTicks(7542),
                            Country = "New Caledonia",
                            FirstName = "Lana",
                            LastName = "Kessler"
                        },
                        new
                        {
                            Id = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            Birthday = new DateTime(2004, 9, 21, 17, 58, 30, 515, DateTimeKind.Utc).AddTicks(2346),
                            Country = "Bhutan",
                            FirstName = "Kari",
                            LastName = "Tillman"
                        },
                        new
                        {
                            Id = new Guid("d25e0bc3-c9a6-45f5-9f54-5bc61569d7e5"),
                            Birthday = new DateTime(1977, 9, 21, 17, 58, 30, 517, DateTimeKind.Utc).AddTicks(2924),
                            Country = "Colombia",
                            FirstName = "Van",
                            LastName = "Wilderman"
                        },
                        new
                        {
                            Id = new Guid("41e16b8b-4b44-4bb2-accb-165a8b1ddcab"),
                            Birthday = new DateTime(1917, 9, 21, 17, 58, 30, 519, DateTimeKind.Utc).AddTicks(2777),
                            Country = "Morocco",
                            FirstName = "Vicki",
                            LastName = "Kunze"
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<int>("BookType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReturnTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ClientId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6700723-a989-4d32-9835-35134ea73ddd"),
                            AuthorId = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            BookType = 0,
                            Description = "Sequi ea id qui sint nesciunt consequatur eum aspernatur et odio possimus architecto laborum iusto est quia qui cumque officiis sint repellat beatae ut adipisci voluptates voluptatibus assumenda adipisci eos et provident nostrum quis porro dolorem necessitatibus pariatur soluta provident.",
                            Genre = "autem",
                            ISBN = "9792539524317",
                            Title = "Molestiae est aut praesentium corporis ipsum inventore laboriosam autem quia."
                        },
                        new
                        {
                            Id = new Guid("ea4516e2-3eda-49aa-8d52-2bed98344d3e"),
                            AuthorId = new Guid("ff826d19-91e0-46c3-89a0-80f1c93cef28"),
                            BookType = 0,
                            Description = "Est mollitia cupiditate in qui rerum sit ut voluptatem et eaque illo tempore nulla eum asperiores et ut ipsum dolorum at modi accusantium explicabo commodi aut assumenda est.",
                            Genre = "tempore",
                            ISBN = "9781777677749",
                            Title = "Sit ut id doloremque aliquid quisquam."
                        },
                        new
                        {
                            Id = new Guid("74a5f80f-9e1e-4a4d-86b7-c5de24303856"),
                            AuthorId = new Guid("41e16b8b-4b44-4bb2-accb-165a8b1ddcab"),
                            BookType = 0,
                            Description = "Eum numquam et quis officiis optio et non ea accusamus voluptatum repudiandae cupiditate quidem ut temporibus ea aspernatur quis tenetur dignissimos sequi velit sint in.",
                            Genre = "officia",
                            ISBN = "9791293638452",
                            Title = "Delectus quae aspernatur et sit."
                        },
                        new
                        {
                            Id = new Guid("cec8125e-4096-4b99-9879-a2e3c9a22a65"),
                            AuthorId = new Guid("d25e0bc3-c9a6-45f5-9f54-5bc61569d7e5"),
                            BookType = 0,
                            Description = "Ad quia ratione aut facere modi quidem quod minima fugit qui nihil corporis labore iusto est libero officia officiis quia est iusto est consequatur omnis at ut officiis illo voluptatem animi neque aliquid doloremque qui iusto minima est nihil commodi quibusdam dolorem quaerat quia molestiae expedita repellendus eaque odit quia voluptatibus quo nobis facilis.",
                            Genre = "eum",
                            ISBN = "9787914205509",
                            Title = "A labore natus aut ad."
                        },
                        new
                        {
                            Id = new Guid("7169e3df-a1e7-462d-89f5-6309adf6b615"),
                            AuthorId = new Guid("d25e0bc3-c9a6-45f5-9f54-5bc61569d7e5"),
                            BookType = 0,
                            Description = "Cum eligendi voluptatum optio delectus accusantium nisi excepturi quae facilis maiores occaecati veniam harum reiciendis quia expedita cum aut maiores facilis similique omnis doloribus vel quia quae ut eos et consequatur vel quo voluptatem quaerat voluptatem accusamus numquam officia et minus et amet ut molestias eos ad officia consequatur ipsum ad ipsa error voluptates est ullam molestias deserunt consequatur qui modi nemo.",
                            Genre = "qui",
                            ISBN = "9799503295273",
                            Title = "Molestiae voluptatem id tenetur vel."
                        },
                        new
                        {
                            Id = new Guid("54f3eeda-84f7-44c2-bb5d-231488137a91"),
                            AuthorId = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            BookType = 0,
                            Description = "Eos accusamus et nihil deserunt culpa expedita ut illo accusamus sit architecto nihil molestiae tempora sunt sunt vitae harum sint saepe assumenda voluptatem molestiae modi expedita molestiae qui reiciendis similique voluptates error quia suscipit ut temporibus eum voluptatem tempora fugiat voluptate eligendi ut quidem et voluptatem porro est voluptate porro ducimus repellat exercitationem architecto nobis architecto eaque animi error distinctio assumenda praesentium dolores et recusandae voluptatem.",
                            Genre = "totam",
                            ISBN = "9795949647058",
                            Title = "Alias ipsam ut odit nostrum sequi illum."
                        },
                        new
                        {
                            Id = new Guid("a6b35bcd-be1b-4341-a82c-2713f70e19f9"),
                            AuthorId = new Guid("41e16b8b-4b44-4bb2-accb-165a8b1ddcab"),
                            BookType = 0,
                            Description = "Non iure placeat consequuntur et sed ut nam officia autem minus fugit enim vitae quidem dolorem hic aut quia itaque.",
                            Genre = "eos",
                            ISBN = "9796625473428",
                            Title = "Saepe dolorem aut velit quo explicabo assumenda et aliquam quia."
                        },
                        new
                        {
                            Id = new Guid("d6c40ee1-b4f3-44f5-81ff-94b55bba1ae0"),
                            AuthorId = new Guid("d25e0bc3-c9a6-45f5-9f54-5bc61569d7e5"),
                            BookType = 0,
                            Description = "Libero veniam eaque quia mollitia sint ut sit non rerum et commodi illum voluptatibus enim quis iusto dolorem voluptatem accusamus quia quibusdam voluptatibus aut est veniam ut animi enim officiis quis eum et sit nihil soluta in sequi quia et ducimus molestiae officia atque id molestiae molestiae in qui aut nisi exercitationem ut est ullam.",
                            Genre = "reprehenderit",
                            ISBN = "9798254585992",
                            Title = "Id doloribus nam corrupti et cumque."
                        },
                        new
                        {
                            Id = new Guid("6807dab3-5e47-4f0a-bab7-77e6919e746d"),
                            AuthorId = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            BookType = 0,
                            Description = "Repudiandae omnis eaque omnis est velit vitae harum quae ullam impedit ut debitis quia laborum odio sit placeat modi dolorem aut delectus repellendus eligendi ut nihil ipsum magni ut facilis ad nisi praesentium aliquam aut quae amet non est odit in labore quaerat quidem rerum accusantium odit aspernatur.",
                            Genre = "tenetur",
                            ISBN = "9790345366572",
                            Title = "Voluptatem minus maxime aperiam est praesentium."
                        },
                        new
                        {
                            Id = new Guid("c7a8568b-8cc6-47a8-ba3b-ceb62be5e6ee"),
                            AuthorId = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            BookType = 0,
                            Description = "Et sunt unde et cum quo ipsam natus harum sit autem esse voluptas aut omnis atque facilis rem inventore veritatis voluptatem quod aliquid quam tempore aut vel omnis ab aut mollitia eum aut quia earum consequuntur quos ea fuga et velit necessitatibus placeat similique est a molestiae sequi.",
                            Genre = "accusantium",
                            ISBN = "9783846479070",
                            Title = "Aut sint ad incidunt."
                        },
                        new
                        {
                            Id = new Guid("f8900264-36b0-4311-93a6-599443e21921"),
                            AuthorId = new Guid("41e16b8b-4b44-4bb2-accb-165a8b1ddcab"),
                            BookType = 0,
                            Description = "Quia corrupti aperiam nesciunt quas fugiat et sunt deserunt repellat ex velit aut aut placeat exercitationem voluptatem quisquam sit consequatur distinctio iure nesciunt odio ipsa.",
                            Genre = "ipsa",
                            ISBN = "9798965806621",
                            Title = "Sequi aperiam excepturi ad sint."
                        },
                        new
                        {
                            Id = new Guid("4110cd1e-daab-45b9-9b9e-81ba2d5b4c1f"),
                            AuthorId = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            BookType = 0,
                            Description = "Dolorem nesciunt numquam harum explicabo similique possimus id quaerat consequuntur expedita minima omnis nesciunt voluptatem est qui est repudiandae nemo dolor nihil suscipit.",
                            Genre = "culpa",
                            ISBN = "9787654806103",
                            Title = "Nostrum quisquam sit vel rem ex ut."
                        },
                        new
                        {
                            Id = new Guid("9db3f32f-1afe-42a4-bae1-0cd1cbffc110"),
                            AuthorId = new Guid("ff826d19-91e0-46c3-89a0-80f1c93cef28"),
                            BookType = 0,
                            Description = "Sed aliquam sint animi perspiciatis rerum optio aut occaecati architecto dolor explicabo sed qui perspiciatis ut non culpa a sed harum quisquam eaque tempora voluptatem culpa asperiores excepturi beatae similique autem beatae quae aut occaecati qui deleniti iste alias possimus adipisci illum voluptatibus praesentium omnis placeat sit id dicta sint.",
                            Genre = "expedita",
                            ISBN = "9781605142593",
                            Title = "Itaque atque autem et exercitationem corporis hic."
                        },
                        new
                        {
                            Id = new Guid("1c84f964-3a82-4ef6-9fb7-989d61a78059"),
                            AuthorId = new Guid("ff826d19-91e0-46c3-89a0-80f1c93cef28"),
                            BookType = 0,
                            Description = "Rerum sunt nihil magnam enim omnis nihil accusantium quisquam qui quasi voluptatibus dolore qui atque enim nisi natus ut optio rerum dolor eveniet sit sit nostrum quis consequatur quia ab similique eos consectetur sed cumque omnis omnis quidem eum aut officia neque omnis ducimus vitae ad nihil deserunt aut ea at eius eaque natus.",
                            Genre = "in",
                            ISBN = "9796136479544",
                            Title = "Veniam impedit et accusamus sit."
                        },
                        new
                        {
                            Id = new Guid("0192be1a-7fa2-49c4-bac3-c88dfa009846"),
                            AuthorId = new Guid("d25e0bc3-c9a6-45f5-9f54-5bc61569d7e5"),
                            BookType = 0,
                            Description = "Doloremque cupiditate enim minus nam minima velit nostrum ut ducimus ut eius placeat alias accusamus pariatur officiis placeat dignissimos et rem in veniam quasi doloribus adipisci velit ut eum labore molestias in nesciunt hic voluptas iste consectetur sequi reiciendis sequi occaecati quas ea vel voluptas atque delectus fugiat libero possimus.",
                            Genre = "qui",
                            ISBN = "9781779722515",
                            Title = "Laborum molestias ipsum et."
                        },
                        new
                        {
                            Id = new Guid("289647c2-c983-4b1c-8705-54e43bd8e6e0"),
                            AuthorId = new Guid("41e16b8b-4b44-4bb2-accb-165a8b1ddcab"),
                            BookType = 0,
                            Description = "Facilis soluta dolorem natus aut incidunt eveniet dolores voluptate voluptas nemo sed fuga ut velit quam maxime cumque iusto et delectus aliquam officia quasi rerum quam iste id quis eos sed quia eveniet eos sed quisquam aut vero magnam ex non quas voluptatem magni sint nulla sint quo rerum aut ipsam quae.",
                            Genre = "architecto",
                            ISBN = "9791527707855",
                            Title = "Similique rerum aperiam velit aut et consequatur dolorem."
                        },
                        new
                        {
                            Id = new Guid("64460962-6988-4974-bbbe-ace95fc56c2e"),
                            AuthorId = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            BookType = 0,
                            Description = "Officia rerum sed omnis perspiciatis quos eos voluptates et rem ratione cupiditate unde dolor earum unde velit eveniet dicta non impedit et delectus libero tempora autem voluptatem accusamus at reprehenderit aut rerum nam eos qui voluptate dolorum et rerum cum.",
                            Genre = "quia",
                            ISBN = "9797876020621",
                            Title = "Ut mollitia ut voluptatibus consequatur suscipit sunt sed."
                        },
                        new
                        {
                            Id = new Guid("b99b46b2-70a1-4900-ab18-d9eef87edaa9"),
                            AuthorId = new Guid("41e16b8b-4b44-4bb2-accb-165a8b1ddcab"),
                            BookType = 0,
                            Description = "Blanditiis enim odit deserunt voluptatem non unde rem et laudantium ipsam quas sed laboriosam corrupti facere sit qui cumque culpa nesciunt molestiae vel est culpa qui debitis voluptatem quia tempora doloremque molestiae nostrum atque.",
                            Genre = "temporibus",
                            ISBN = "9798920273994",
                            Title = "Necessitatibus similique dolorem."
                        },
                        new
                        {
                            Id = new Guid("a3f3d438-f93e-43af-9e37-dffd9c9f98f6"),
                            AuthorId = new Guid("d25e0bc3-c9a6-45f5-9f54-5bc61569d7e5"),
                            BookType = 0,
                            Description = "Iure hic quaerat magni labore doloribus tempore harum et nostrum quos sunt harum tenetur dolor facilis sunt in et tempora consequatur eligendi architecto eveniet sapiente dolore ipsam impedit quam mollitia dolores rerum est maxime veritatis commodi libero totam et consequuntur non quia id commodi veritatis repellat dicta officiis distinctio facilis corporis ab saepe voluptates laborum asperiores voluptatibus fugit provident.",
                            Genre = "et",
                            ISBN = "9798104083852",
                            Title = "Odio aut autem aut facere velit velit quia."
                        },
                        new
                        {
                            Id = new Guid("397eb421-77d7-44ee-a2d6-8d3787d8bc91"),
                            AuthorId = new Guid("41e16b8b-4b44-4bb2-accb-165a8b1ddcab"),
                            BookType = 0,
                            Description = "Ipsam qui eos iusto nulla eaque suscipit ratione dolorem vero voluptatibus libero quo rerum a recusandae commodi harum iste rerum nemo veritatis ut eligendi quo quasi recusandae sit qui vel minus facilis porro consequatur quam voluptate reprehenderit eum consequatur dolor ad voluptatem delectus dolorem et dolorem aut omnis dolorem provident voluptates tempora ab.",
                            Genre = "perspiciatis",
                            ISBN = "9788298404427",
                            Title = "Dolores aperiam ad nobis omnis impedit neque dolorem."
                        },
                        new
                        {
                            Id = new Guid("ee7b1118-3dc1-4de0-8614-6f9af9439770"),
                            AuthorId = new Guid("41e16b8b-4b44-4bb2-accb-165a8b1ddcab"),
                            BookType = 0,
                            Description = "Recusandae expedita harum deserunt labore accusantium expedita iusto optio reprehenderit et eum aliquam natus repellat aperiam sint aut eum et nemo aperiam et excepturi fuga aspernatur quasi saepe laboriosam expedita libero quam vitae aut qui vel odit at aut est ut praesentium repellat mollitia corporis cum saepe ut vel voluptatibus rem sed unde earum ab enim laudantium deserunt est est.",
                            Genre = "vero",
                            ISBN = "9794943800421",
                            Title = "Ea asperiores aut similique."
                        },
                        new
                        {
                            Id = new Guid("4a26985a-614f-42a0-82ff-4046681bd41e"),
                            AuthorId = new Guid("d25e0bc3-c9a6-45f5-9f54-5bc61569d7e5"),
                            BookType = 0,
                            Description = "Eius voluptatem rerum eius minima ut nulla accusantium voluptatem accusamus earum iusto repudiandae qui aut iusto velit molestiae nam distinctio magni perspiciatis qui tenetur voluptas et dolores aperiam tempora officiis consectetur dolor nobis ea sint eveniet dolor ut sit.",
                            Genre = "eius",
                            ISBN = "9784069429170",
                            Title = "Dolor maiores doloremque tempore."
                        },
                        new
                        {
                            Id = new Guid("ae187c60-8278-473b-a799-71b2959b434f"),
                            AuthorId = new Guid("e0a3724e-c4fe-4f99-95cf-48f359541fb0"),
                            BookType = 0,
                            Description = "Repellendus nihil totam enim minima quis est sunt beatae vel est et blanditiis rerum dolorem quia accusantium est quo molestiae hic perferendis consequatur quos quis fugiat esse consequatur et debitis qui impedit soluta et consequatur voluptas sint veniam repellat.",
                            Genre = "voluptatem",
                            ISBN = "9784393258354",
                            Title = "Et enim ullam maxime non dolor consequatur possimus accusantium."
                        },
                        new
                        {
                            Id = new Guid("a2b6a85c-996e-4e29-a90a-7c554cd7e53d"),
                            AuthorId = new Guid("d25e0bc3-c9a6-45f5-9f54-5bc61569d7e5"),
                            BookType = 0,
                            Description = "Possimus quod ipsam aut amet voluptas perspiciatis voluptate ipsam quasi distinctio accusamus in omnis non dolorem omnis mollitia doloremque vel et accusamus nisi facere cupiditate libero quibusdam perferendis fugit reprehenderit eius quaerat sed aut alias ut aperiam ut labore optio occaecati quia et totam voluptas qui quia autem et excepturi omnis quibusdam officia voluptas nihil nostrum facilis repellat itaque dolores et temporibus tenetur alias veniam architecto eum optio qui molestiae.",
                            Genre = "et",
                            ISBN = "9786460027122",
                            Title = "A dolor architecto eligendi."
                        },
                        new
                        {
                            Id = new Guid("74cf362a-aea4-41b8-b7fd-5271ae8ba589"),
                            AuthorId = new Guid("ff826d19-91e0-46c3-89a0-80f1c93cef28"),
                            BookType = 0,
                            Description = "Sit quasi ad tempore quibusdam voluptatem voluptatum aspernatur dicta consequatur dolore ut corporis aut ut commodi illo dolorem qui corrupti soluta optio ipsa non explicabo dolor minus quasi et.",
                            Genre = "eum",
                            ISBN = "9792370647343",
                            Title = "Non vel excepturi voluptas odit iste velit."
                        },
                        new
                        {
                            Id = new Guid("7ecb1565-a863-4e4c-ae16-7e754053fb45"),
                            AuthorId = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            BookType = 0,
                            Description = "Aut molestiae nulla maiores quia recusandae amet sit optio iure est explicabo autem quam beatae dicta quas quisquam illo assumenda non perferendis similique officiis asperiores qui neque voluptas ut qui dolore cumque sapiente alias laboriosam et illum officiis saepe fugit voluptatibus dolor id veniam dolorem omnis optio a sint amet nihil qui sed quo qui cum cupiditate libero nulla dolorem et et quasi harum eaque fugit consequatur sunt eligendi.",
                            Genre = "vitae",
                            ISBN = "9786580400300",
                            Title = "Vitae voluptate et ad non aperiam iure sit numquam."
                        },
                        new
                        {
                            Id = new Guid("66178617-3bc3-4c06-94f1-38717f75c59c"),
                            AuthorId = new Guid("ff826d19-91e0-46c3-89a0-80f1c93cef28"),
                            BookType = 0,
                            Description = "Corrupti expedita est at exercitationem optio placeat voluptatum non et autem rerum iusto eum perferendis molestiae dicta veniam quia qui odit deleniti fugiat ipsa.",
                            Genre = "nam",
                            ISBN = "9795832611623",
                            Title = "Possimus odit esse sint."
                        },
                        new
                        {
                            Id = new Guid("de15580f-492c-4ef1-ae23-94700d2824ad"),
                            AuthorId = new Guid("ff826d19-91e0-46c3-89a0-80f1c93cef28"),
                            BookType = 0,
                            Description = "Sed aut reprehenderit reprehenderit eos possimus veniam voluptatem eum corrupti nemo nostrum iste minus laboriosam aut rerum nihil reprehenderit dolorum porro eos nisi quidem voluptates enim reprehenderit nemo qui quis rerum praesentium consequatur nulla sapiente cumque nihil cum eaque pariatur at voluptas ut fugit eum ducimus quas consequatur repudiandae expedita inventore dolore aut possimus et pariatur pariatur et quia omnis illum placeat facilis quis odio.",
                            Genre = "harum",
                            ISBN = "9794079819304",
                            Title = "Nesciunt maiores itaque."
                        },
                        new
                        {
                            Id = new Guid("4656ec65-1e30-4977-ad99-52c3ba22dfe3"),
                            AuthorId = new Guid("41e16b8b-4b44-4bb2-accb-165a8b1ddcab"),
                            BookType = 0,
                            Description = "Magni iure saepe temporibus vero vel ut magni eum aspernatur similique voluptatem optio minus sunt nulla magnam consequatur quae odit doloribus sit expedita reprehenderit distinctio et ducimus enim veniam.",
                            Genre = "dolor",
                            ISBN = "9783365431658",
                            Title = "Porro nihil molestiae nemo deleniti."
                        },
                        new
                        {
                            Id = new Guid("250775c8-0fd9-4520-ba88-414e7cd545e1"),
                            AuthorId = new Guid("41e16b8b-4b44-4bb2-accb-165a8b1ddcab"),
                            BookType = 0,
                            Description = "Laboriosam dolorem quia laboriosam et accusamus nostrum atque officiis sed rerum minima consequatur nihil quae et et sunt non ut eum doloribus itaque quam quos adipisci unde qui nesciunt possimus ex sapiente qui nam facere accusantium repudiandae est quis eveniet ea accusamus.",
                            Genre = "maxime",
                            ISBN = "9781266472770",
                            Title = "Praesentium voluptatem labore exercitationem similique nihil nihil in veritatis dolore."
                        },
                        new
                        {
                            Id = new Guid("b10b74cf-5de0-4c13-8bbd-72fbdddaf0b3"),
                            AuthorId = new Guid("e0a3724e-c4fe-4f99-95cf-48f359541fb0"),
                            BookType = 0,
                            Description = "Aliquid assumenda alias quos aut voluptate qui at quisquam sequi assumenda quaerat qui tenetur dolor et sequi ratione autem non delectus expedita architecto minus et.",
                            Genre = "sit",
                            ISBN = "9786999765960",
                            Title = "Velit dolore necessitatibus blanditiis amet expedita nisi nam quod."
                        },
                        new
                        {
                            Id = new Guid("f635eccf-c9c5-47ff-b113-454bfe09876f"),
                            AuthorId = new Guid("41e16b8b-4b44-4bb2-accb-165a8b1ddcab"),
                            BookType = 0,
                            Description = "Rerum rerum rerum quibusdam aut impedit ut omnis distinctio porro est at doloribus velit ad ab et neque sint vero repellendus aspernatur iusto et ducimus nisi quaerat neque sed perferendis quisquam ratione deserunt velit sed minus nihil et.",
                            Genre = "aut",
                            ISBN = "9798342132268",
                            Title = "Repudiandae beatae velit rerum fugiat culpa aut dolorem."
                        },
                        new
                        {
                            Id = new Guid("a003a588-e3fc-46b8-9d20-1817032f0e5d"),
                            AuthorId = new Guid("41e16b8b-4b44-4bb2-accb-165a8b1ddcab"),
                            BookType = 0,
                            Description = "Quasi inventore minima placeat error aut et praesentium aperiam eum impedit quaerat earum quam architecto nemo qui sequi aut delectus aliquid aut architecto delectus optio voluptatem est autem et a neque sit qui sint vitae tenetur quo assumenda illo dolore quibusdam sunt exercitationem culpa occaecati dolorem ut facere in molestias voluptatibus laboriosam ut unde minus.",
                            Genre = "tenetur",
                            ISBN = "9786819146733",
                            Title = "Vitae numquam sed cumque."
                        },
                        new
                        {
                            Id = new Guid("0e90bd34-993d-41c1-94b5-4812c80d0364"),
                            AuthorId = new Guid("d25e0bc3-c9a6-45f5-9f54-5bc61569d7e5"),
                            BookType = 0,
                            Description = "Consequatur quia autem ratione molestias dignissimos ut rerum vero laudantium repudiandae ea eligendi sunt magni sint est omnis illo voluptas sed aut necessitatibus temporibus molestias beatae eveniet quasi et et doloribus quidem suscipit voluptatibus aut officiis ut praesentium porro ullam optio et enim eligendi iusto nam dolores itaque fugit aut alias eveniet.",
                            Genre = "fuga",
                            ISBN = "9792144428925",
                            Title = "Voluptatem consequatur nobis ullam quae ad et."
                        },
                        new
                        {
                            Id = new Guid("17aa0bac-4c90-4012-aed8-4fcfdc399f16"),
                            AuthorId = new Guid("e0a3724e-c4fe-4f99-95cf-48f359541fb0"),
                            BookType = 0,
                            Description = "Maxime voluptatem aut consectetur debitis ut ea sunt deserunt officia harum et quam voluptatem fuga sunt est sunt dolores quas consectetur beatae.",
                            Genre = "et",
                            ISBN = "9789068512229",
                            Title = "Alias similique sed."
                        },
                        new
                        {
                            Id = new Guid("5ceb5b5a-1bda-4fe1-9b90-0f6818573ade"),
                            AuthorId = new Guid("ff826d19-91e0-46c3-89a0-80f1c93cef28"),
                            BookType = 0,
                            Description = "Tenetur dolore praesentium optio inventore quo perferendis hic necessitatibus voluptatibus laborum quia aliquid dicta totam et omnis nobis magni laborum et deleniti vitae ut quos consequatur et sequi eos non sit fugiat vel omnis sunt necessitatibus dignissimos sit qui qui perferendis labore debitis quo ab quaerat id repellendus aperiam odit nam laudantium id accusantium eligendi id voluptatibus quo quos accusamus.",
                            Genre = "quia",
                            ISBN = "9795937195479",
                            Title = "Nihil dolor officia expedita rem veritatis molestiae."
                        },
                        new
                        {
                            Id = new Guid("03edb50f-dc67-449f-a7f7-22ab2e05885b"),
                            AuthorId = new Guid("d25e0bc3-c9a6-45f5-9f54-5bc61569d7e5"),
                            BookType = 0,
                            Description = "Quis nulla temporibus quidem quia omnis pariatur cum aut eveniet impedit officiis labore et quae voluptatem suscipit quaerat assumenda quo possimus saepe et modi et esse molestiae aliquam reiciendis neque voluptate ullam debitis neque voluptates similique et dicta reiciendis veniam ab molestiae eum et rerum repudiandae corporis dignissimos rerum qui.",
                            Genre = "labore",
                            ISBN = "9792341655926",
                            Title = "Recusandae blanditiis sed animi quam non qui aut et."
                        },
                        new
                        {
                            Id = new Guid("21ed6038-96ea-40f8-8ae8-6ade4cb03f7d"),
                            AuthorId = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            BookType = 0,
                            Description = "Sit ipsum et eos quia aliquid laborum labore eaque voluptates labore harum est quod enim quod asperiores ea ducimus nesciunt consequatur consectetur amet cumque aut eaque officia assumenda impedit a unde maxime at exercitationem sapiente et odit veniam.",
                            Genre = "est",
                            ISBN = "9785339117018",
                            Title = "Et quas quidem."
                        },
                        new
                        {
                            Id = new Guid("a763ee55-2093-4dfa-b499-c7fc3c908a28"),
                            AuthorId = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            BookType = 0,
                            Description = "Ea perspiciatis veniam exercitationem qui quisquam et eaque suscipit harum cum corporis iste velit qui repudiandae optio quaerat ut laboriosam nemo at libero libero cupiditate rerum et cum beatae ut repudiandae voluptatum dolor officia neque mollitia qui similique ipsa nemo tempora rem in optio nostrum architecto ipsam totam est blanditiis dignissimos magni voluptas et ad.",
                            Genre = "error",
                            ISBN = "9794570747793",
                            Title = "Expedita reprehenderit corporis tempore reprehenderit eum possimus quam et."
                        },
                        new
                        {
                            Id = new Guid("d98ed224-0c02-4522-a626-c1d09f43f396"),
                            AuthorId = new Guid("e0a3724e-c4fe-4f99-95cf-48f359541fb0"),
                            BookType = 0,
                            Description = "Omnis accusantium possimus ea qui qui nam veniam eaque sapiente at ipsa explicabo saepe nostrum nihil tempora tempore possimus repellendus ipsa placeat unde blanditiis et minus est ipsam provident unde ea qui quos provident consequatur est.",
                            Genre = "nostrum",
                            ISBN = "9794712064702",
                            Title = "Tenetur placeat dolores debitis eum qui."
                        },
                        new
                        {
                            Id = new Guid("514e5954-3b9a-46dc-992b-07bffb44ffca"),
                            AuthorId = new Guid("e0a3724e-c4fe-4f99-95cf-48f359541fb0"),
                            BookType = 0,
                            Description = "Aperiam laboriosam deserunt eaque aut fugit sapiente assumenda dolores vel culpa ipsum ipsum sint omnis delectus nihil veritatis amet perferendis deleniti illum magni vel deserunt voluptatem ipsam sit rerum atque atque iure possimus porro odio aspernatur aut reprehenderit odit rerum ut doloremque dolores et adipisci quo eos veritatis assumenda corrupti.",
                            Genre = "velit",
                            ISBN = "9782260355748",
                            Title = "Eos quisquam qui quod ipsa rem vero explicabo odio."
                        },
                        new
                        {
                            Id = new Guid("34fbc964-ee79-465a-b03a-6e3625e83ad2"),
                            AuthorId = new Guid("d25e0bc3-c9a6-45f5-9f54-5bc61569d7e5"),
                            BookType = 0,
                            Description = "Minima debitis excepturi ex nostrum perspiciatis sunt aspernatur excepturi ut molestias minus quia recusandae ut quasi laborum distinctio ab et veniam deleniti voluptates maxime provident amet sed incidunt voluptatem qui nostrum soluta fuga est sint praesentium voluptas voluptas sunt sed recusandae distinctio sed provident occaecati illum nostrum aperiam culpa voluptate dolores repudiandae distinctio esse et aut aut rem autem quae voluptate consequatur unde ab.",
                            Genre = "reiciendis",
                            ISBN = "9793871774385",
                            Title = "Dolor eum sed quae autem ut vel exercitationem voluptatum."
                        },
                        new
                        {
                            Id = new Guid("e4a8cc01-7737-4074-bd63-695a9eb7e574"),
                            AuthorId = new Guid("ff826d19-91e0-46c3-89a0-80f1c93cef28"),
                            BookType = 0,
                            Description = "Sit dolorem magnam nobis molestias dolore praesentium voluptatem quia sapiente suscipit velit amet eos quam sed quo facilis earum amet et id molestiae mollitia est in dicta soluta sapiente voluptatem omnis expedita adipisci doloremque reiciendis autem qui sunt assumenda iusto facilis quos officia reprehenderit ut facilis similique impedit voluptatem nihil deleniti rerum et autem ad debitis voluptas eum nisi inventore ratione sint.",
                            Genre = "aut",
                            ISBN = "9783483676603",
                            Title = "Doloribus architecto error eligendi."
                        },
                        new
                        {
                            Id = new Guid("0b7a6916-8e8c-4845-8fcd-d4ffc3fc2004"),
                            AuthorId = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            BookType = 0,
                            Description = "Qui consequatur voluptatem ullam aut aut cupiditate ut suscipit enim minus recusandae voluptatum eligendi nulla et mollitia ducimus reprehenderit dicta sint cupiditate voluptates sit delectus nihil rerum vero hic assumenda quo rem corrupti quia aliquam quia et dolor cupiditate corrupti eos ducimus sint et praesentium porro rerum nihil voluptatem.",
                            Genre = "autem",
                            ISBN = "9797167938222",
                            Title = "Qui consequatur et dolor aspernatur eum."
                        },
                        new
                        {
                            Id = new Guid("cdbfae59-52bd-4576-a6a7-af0814f989f1"),
                            AuthorId = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            BookType = 0,
                            Description = "Nostrum esse pariatur odio labore nihil aspernatur amet illo ea harum veniam minus dolore aut eum voluptas molestias veniam sed vel quo in vel est sed consequatur deleniti quisquam expedita voluptas qui odio dolores ut illo vel velit consectetur quos facilis quo sed omnis totam enim perspiciatis sit sed incidunt aut.",
                            Genre = "odit",
                            ISBN = "9787652535562",
                            Title = "Non inventore est aliquid sint."
                        },
                        new
                        {
                            Id = new Guid("472fd710-9d7b-48ad-8c21-f10835d3e78f"),
                            AuthorId = new Guid("e0a3724e-c4fe-4f99-95cf-48f359541fb0"),
                            BookType = 0,
                            Description = "Nobis alias aliquam est id provident fugiat id reiciendis adipisci ea iure aut sequi non amet et qui aut est incidunt enim ex et voluptas ea non ab ea sunt non consectetur optio vel ratione impedit corporis dicta quo qui iusto nulla vero et id illo est minima quidem illo voluptas maxime sint sapiente cupiditate molestiae qui.",
                            Genre = "rem",
                            ISBN = "9784351190207",
                            Title = "Atque eaque inventore tenetur."
                        },
                        new
                        {
                            Id = new Guid("8687d3b4-5aed-4958-9710-4c13d2dfde41"),
                            AuthorId = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            BookType = 0,
                            Description = "Occaecati sapiente ea dolores unde est porro recusandae quidem sunt quia aliquam debitis autem fuga ipsum recusandae consequuntur qui sit ratione delectus qui distinctio ab magni voluptatem minus aut quia reprehenderit hic praesentium nobis vel eum sit voluptates dolores est reiciendis ex molestiae quo unde mollitia numquam necessitatibus ullam est voluptatem qui amet sit voluptatum iure deserunt reiciendis in.",
                            Genre = "sit",
                            ISBN = "9796776363685",
                            Title = "Voluptas sit eaque voluptate velit nobis autem modi et."
                        },
                        new
                        {
                            Id = new Guid("1db9d341-690f-40ac-a265-365af51c34d9"),
                            AuthorId = new Guid("e0a3724e-c4fe-4f99-95cf-48f359541fb0"),
                            BookType = 0,
                            Description = "Non nesciunt eaque optio quasi nisi vitae fugit quia natus quo accusamus soluta quisquam consequatur quam animi placeat quasi earum consequatur id blanditiis autem at quis id vel laudantium praesentium voluptatem ut quia laboriosam perspiciatis ut earum eum id dignissimos quidem iste in quasi ipsum ab molestias quia quam quibusdam qui repudiandae magnam quisquam omnis qui minus.",
                            Genre = "ad",
                            ISBN = "9794520760094",
                            Title = "Omnis sapiente est repudiandae."
                        },
                        new
                        {
                            Id = new Guid("6bac6908-132f-4acb-a9c7-4b83b883bf9e"),
                            AuthorId = new Guid("c23364a6-b1f4-4bdb-a743-67820ba1f66b"),
                            BookType = 0,
                            Description = "Quia ullam sequi modi ipsa sint dolor quisquam sit iusto corporis reiciendis reprehenderit eum quo quo eum aut voluptatem eaque qui quam error nostrum aspernatur qui asperiores aut tenetur impedit magni ipsam perferendis accusamus voluptate voluptates et rerum fuga temporibus sed cumque assumenda est enim in delectus dolor non consectetur iure reprehenderit culpa in ut tempore a non quaerat est voluptas quaerat explicabo reprehenderit doloribus.",
                            Genre = "consequatur",
                            ISBN = "9780088391238",
                            Title = "Libero minima doloremque libero enim aperiam."
                        },
                        new
                        {
                            Id = new Guid("0f80a27e-d2ed-4222-ab3e-fbb556ab64e4"),
                            AuthorId = new Guid("e0a3724e-c4fe-4f99-95cf-48f359541fb0"),
                            BookType = 0,
                            Description = "Porro explicabo aperiam eaque nam voluptate dicta laudantium est est facere dolor voluptates laborum neque beatae eius ducimus aut laudantium non ut odit quisquam vero reiciendis cupiditate perferendis enim eos et aut nemo optio laudantium in quas possimus corrupti enim ut animi corporis laboriosam laudantium cupiditate deserunt dolorem officia in vel exercitationem possimus vitae tempora.",
                            Genre = "impedit",
                            ISBN = "9782008592404",
                            Title = "Distinctio iusto sapiente animi molestiae."
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.PermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Create"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Update"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Delete"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Read"
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.UserAccessGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAccessGroup");

                    b.HasData(
                        new
                        {
                            GroupId = 2,
                            UserId = new Guid("3a2ba859-2f41-4938-9ab1-439c55cec181"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = new Guid("ca0882f0-8bd5-4ff3-839e-0ee4e1c8b878"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = new Guid("33e353fe-2ea2-447d-b5c3-49e334de061f"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = new Guid("3c154de9-8af7-4e21-9d25-a604980aa88b"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = new Guid("6334c50b-eb6c-41f1-b752-d232054656cf"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 1,
                            UserId = new Guid("797b66f0-ee97-4ab3-8ad9-c383cb113bbf"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = new Guid("797b66f0-ee97-4ab3-8ad9-c383cb113bbf"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a2ba859-2f41-4938-9ab1-439c55cec181"),
                            Email = "Rodolfo22@yahoo.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEBbVe+IXyXFKIj27SSNgvvF0Toc/r9ZubY+3Oq1WyzX8UcQt22MSkWuhyksha672qA==",
                            UserName = "Rodolfo44"
                        },
                        new
                        {
                            Id = new Guid("ca0882f0-8bd5-4ff3-839e-0ee4e1c8b878"),
                            Email = "Annette25@hotmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEOY7IaUpZ2yr2pLM9qraHXku9Bkm7htfsfgjkcIE7P7DGprssdwbglDDKK0cSshzaA==",
                            UserName = "Annette_Bayer23"
                        },
                        new
                        {
                            Id = new Guid("33e353fe-2ea2-447d-b5c3-49e334de061f"),
                            Email = "Antonia86@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEGPkEgSr3TR7xKXMnM+NsO94fg3i3WJsjlAVA8KiRhnBnt+Wsm+4qiqTTI3rK2Mypg==",
                            UserName = "Antonia_Dicki"
                        },
                        new
                        {
                            Id = new Guid("3c154de9-8af7-4e21-9d25-a604980aa88b"),
                            Email = "Santiago6@hotmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEF5VCP7IhbRCD8C+gADuQImf8YCn+xu9wMl/3TECckWZ8UX1ET3xXur7MsODglW37w==",
                            UserName = "Santiago75"
                        },
                        new
                        {
                            Id = new Guid("6334c50b-eb6c-41f1-b752-d232054656cf"),
                            Email = "Ryan69@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEHFXrGk2CxCWgFxJPSOlszpL/WB5SMqVtQXd2g16cPXokMlIzBcFkwTYTIaBjD2qcA==",
                            UserName = "Ryan_Bailey"
                        },
                        new
                        {
                            Id = new Guid("797b66f0-ee97-4ab3-8ad9-c383cb113bbf"),
                            Email = "admin@admin.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEAY0fjAYzO2pKqIlTnJtvk9fOigwyY3gLLFj4zBoURG2e0FIZlUOa4vfDbelHsc7rA==",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.AccessGroupPermission", b =>
                {
                    b.HasOne("Library.DataAccess.DataBase.Entities.AccessGroupEntity", "Group")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.DataAccess.DataBase.Entities.PermissionEntity", "Permission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.BookEntity", b =>
                {
                    b.HasOne("Library.DataAccess.DataBase.Entities.AuthorEntity", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Library.DataAccess.DataBase.Entities.UserEntity", "User")
                        .WithMany("Books")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.RefreshToken", b =>
                {
                    b.HasOne("Library.DataAccess.DataBase.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.UserAccessGroup", b =>
                {
                    b.HasOne("Library.DataAccess.DataBase.Entities.AccessGroupEntity", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.DataAccess.DataBase.Entities.UserEntity", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.AccessGroupEntity", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.AuthorEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.PermissionEntity", b =>
                {
                    b.Navigation("GroupPermissions");
                });

            modelBuilder.Entity("Library.DataAccess.DataBase.Entities.UserEntity", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
